### ISSUE TITLE
The section reference syntax breaks legitimate code

### ISSUE THREAD

**Issue by llee454** [jostylr/litpro#3]
For example: `linkElement.addClass ('search_pagination_page_link_radius_' + radius);` In this example, the trailing underscore should not be interpreted as the start of a section reference. But, there is no natural way to circumvent this misinterpretation.

**Comment by jostylr** [comment]
You can use a backslash:  `linkElement.addClass ('search_pagination_page_link_radius\_' + radius);`

One can also insert unicode value such as `\u005f` though that seems a bit more awkward.
